#!/usr/bin/env node
/**
 * Local Worker — watches Firestore for jobs with mode:'local', runs them locally.
 * No timeout constraints. Starts automatically via launchd or alongside dev server.
 *
 * Usage: node scripts/local-worker.mjs
 * Reads env from .env.local + .env.vercel.local
 */

import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import https from 'node:https';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

// ── Load env ─────────────────────────────────────────────────────────────────

function loadEnvFile(path) {
  if (!existsSync(path)) return {};
  const vars = {};
  for (const line of readFileSync(path, 'utf-8').split('\n')) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=["']?([\s\S]*?)["']?\s*$/);
    if (m) vars[m[1]] = m[2];
  }
  return vars;
}

const env = {
  ...loadEnvFile(resolve(ROOT, '.env.local')),
  ...loadEnvFile(resolve(ROOT, '.env.vercel.local')),
};

// The Claude Agent SDK reads CLAUDE_CODE_OAUTH_TOKEN from process.env directly,
// so promote it across from the .env.local-loaded `env` map.
if (env.CLAUDE_CODE_OAUTH_TOKEN && !process.env.CLAUDE_CODE_OAUTH_TOKEN) {
  process.env.CLAUDE_CODE_OAUTH_TOKEN = env.CLAUDE_CODE_OAUTH_TOKEN;
}

// API key no longer required — worker uses claude CLI (Max subscription)
const API_KEY = env.ANTHROPIC_API_KEY?.trim() ?? '';

const PROJECT_ID = env.FIREBASE_PROJECT_ID || 'aksharpith-translator';
const CLIENT_EMAIL = env.FIREBASE_CLIENT_EMAIL;
const PRIVATE_KEY = env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, '\n');

if (!CLIENT_EMAIL || !PRIVATE_KEY) {
  console.error('Missing FIREBASE_CLIENT_EMAIL or FIREBASE_PRIVATE_KEY');
  process.exit(1);
}

// ── Firebase Admin ───────────────────────────────────────────────────────────

import { initializeApp, cert, getApps } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';

if (getApps().length === 0) {
  initializeApp({ credential: cert({ projectId: PROJECT_ID, clientEmail: CLIENT_EMAIL, privateKey: PRIVATE_KEY }) });
}
const db = getFirestore();

// ── Pipeline config ──────────────────────────────────────────────────────────

const SONNET = 'claude-sonnet-4-20250514';
const BATCH = 5;
const POLL_INTERVAL = 5_000;
const SDK_MAX_RETRIES = 2;
const SDK_RETRY_DELAY_MS = 5_000;

// Optional admin-only telemetry (mirrors lib/pipeline.ts). When 'true', the
// worker fires off a non-blocking reviewer call per chunk and stores the
// score under translations/<id>.adminTelemetry. Never reaches the user view.
const ENABLE_REVIEWER_TELEMETRY = (env.ENABLE_REVIEWER_TELEMETRY ?? process.env.ENABLE_REVIEWER_TELEMETRY) === 'true';

// ── Load rules + prompts via tsx ─────────────────────────────────────────────
// The translator/smoother system prompts are built from the TypeScript rules
// module. The reviewer prompt is loaded only when telemetry is enabled.

let rulesModule;
try {
  const { execSync } = await import('node:child_process');
  // Single-line eval to keep tsx/esbuild from interpreting \n as a TS source escape.
  const rulesScript = `import { buildTranslatorSystem, buildReviewerSystem, buildSmootherSystem } from '${ROOT}/lib/rules/index.ts'; console.log(JSON.stringify({ TRANSLATOR_SYSTEM: buildTranslatorSystem(), SMOOTHER_SYSTEM: buildSmootherSystem(), REVIEWER_SYSTEM: buildReviewerSystem() }));`;
  const result = execSync(`npx tsx -e ${JSON.stringify(rulesScript)}`, {
    encoding: 'utf-8', cwd: ROOT, maxBuffer: 5 * 1024 * 1024,
    env: { ...process.env, ...env },
  });
  rulesModule = JSON.parse(result.trim());
} catch (e) {
  console.error('Failed to load rules via tsx. Falling back to inline prompts.');
  console.error(e.message);
  rulesModule = {
    TRANSLATOR_SYSTEM: 'You are a trustee of the parampara. Translate Gujarati to English with fidelity to BAPS Swaminarayan editorial rules. Output ONLY <translation>...</translation><flags>...</flags>.',
    SMOOTHER_SYSTEM: 'I am working on improving a translation of a non-fiction historical biography for better readability. Keep direct quotes, transliterated verses and proper nouns verbatim. Output ONLY <smoothed>...</smoothed>.',
    REVIEWER_SYSTEM: 'You are a translation reviewer. Return JSON with totalScore, revised, certifiable.',
  };
}

const { TRANSLATOR_SYSTEM, SMOOTHER_SYSTEM, REVIEWER_SYSTEM } = rulesModule;

// ── Claude Agent SDK ─────────────────────────────────────────────────────────
// Auth is via CLAUDE_CODE_OAUTH_TOKEN env var (loaded from .env.local at top of
// this file). Generated by `claude setup-token` — 1-year lifetime.
//
// Why SDK and not the raw `claude` CLI?
//   The CLI is the agentic IDE shell. Even with `-p`, it loads hooks/LSP/MCP/
//   plugins/CLAUDE.md auto-discovery and runs the agent loop. Under non-trivial
//   prompts it opens 19+ TCP connections and hangs at the 5-min Node timeout.
//   The SDK calls Anthropic directly — clean HTTP, no agent overhead.
//
// We disable all built-in tools and cap maxTurns at 1 so query() acts as a
// pure system+user → text completion — no Read/Edit/Bash/Grep, no agent loop.

import { query } from '@anthropic-ai/claude-agent-sdk';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';

if (!process.env.CLAUDE_CODE_OAUTH_TOKEN) {
  console.error('Missing CLAUDE_CODE_OAUTH_TOKEN. Run `claude setup-token` and add to .env.local.');
  process.exit(1);
}

// Isolated cwd keeps the SDK from auto-discovering workspace CLAUDE.md / .claude/.
const SDK_CWD = mkdtempSync(`${tmpdir()}/aksharpith-sdk-`);

async function callClaudeOnce(params) {
  const userPrompt = params.messages.map(m => typeof m.content === 'string' ? m.content : '').join('\n');

  const q = query({
    prompt: userPrompt,
    options: {
      systemPrompt: params.system,
      model: params.model,
      tools: [],                       // pure text completion — no Read/Edit/Bash/etc.
      maxTurns: 1,                     // single response, no agent loop
      cwd: SDK_CWD,
      permissionMode: 'bypassPermissions',
    },
  });

  let text = '';
  let errorKind = null;
  for await (const msg of q) {
    if (msg.type === 'assistant') {
      if (msg.error) errorKind = msg.error;
      for (const block of msg.message.content ?? []) {
        if (block.type === 'text' && typeof block.text === 'string') text += block.text;
      }
    } else if (msg.type === 'result' && msg.subtype !== 'success') {
      errorKind = errorKind ?? msg.subtype;
    }
  }

  if (errorKind) throw new Error(`Claude SDK error: ${errorKind}`);
  if (!text.trim()) throw new Error('Empty response from Claude SDK');
  return text;
}

async function callClaude(params) {
  let lastErr;
  for (let attempt = 0; attempt <= SDK_MAX_RETRIES; attempt++) {
    try {
      return await callClaudeOnce(params);
    } catch (err) {
      lastErr = err;
      console.error(`  [callClaude] attempt ${attempt + 1}/${SDK_MAX_RETRIES + 1} failed: ${err.message}`);
      if (attempt < SDK_MAX_RETRIES) {
        await new Promise(r => setTimeout(r, SDK_RETRY_DELAY_MS * (attempt + 1)));
      }
    }
  }
  throw lastErr;
}

// ── Chunker ──────────────────────────────────────────────────────────────────

function isVerseBlock(para) {
  const lines = para.split('\n').map(l => l.trim()).filter(Boolean);
  if (lines.length < 2) return false;
  const quotedVerse = lines.some(l => /^[\u201c\u201d"'\u2018\u2019]/.test(l) && /[āīūṛṅñṭḍṇśṣḥ]/.test(l));
  const avgLen = lines.reduce((s, l) => s + l.length, 0) / lines.length;
  const similarLength = lines.length >= 2 && lines.every(l => Math.abs(l.length - avgLen) < avgLen * 0.5);
  const diacriticLines = lines.filter(l => /[āīūṛṅñṭḍṇśṣḥ]/.test(l)).length;
  const mostlyDiacritic = diacriticLines >= lines.length * 0.5;
  return quotedVerse || (similarLength && mostlyDiacritic);
}

function deterministicChunk(text) {
  const trimmed = text.trim();
  if (!trimmed) return [];
  const totalWords = trimmed.split(/\s+/).filter(Boolean).length;
  if (totalWords <= 500) return [trimmed];

  let rawParagraphs = trimmed.split(/\n\s*\n/);
  const hasGiantPara = rawParagraphs.some(p => p.trim().split(/\s+/).length > 500);
  if (hasGiantPara) rawParagraphs = trimmed.split(/\n/).filter(l => l.trim());

  const groups = [];
  let pendingVerse = null;
  for (const para of rawParagraphs) {
    const p = para.trim();
    if (!p) continue;
    if (isVerseBlock(p)) {
      if (groups.length > 0) groups[groups.length - 1] += '\n\n' + p;
      else pendingVerse = pendingVerse ? pendingVerse + '\n\n' + p : p;
    } else {
      if (pendingVerse) { groups.push(pendingVerse + '\n\n' + p); pendingVerse = null; }
      else groups.push(p);
    }
  }
  if (pendingVerse) groups.push(pendingVerse);

  const chunks = [];
  let current = [], currentWords = 0;
  for (const group of groups) {
    const groupWords = group.split(/\s+/).length;
    if (currentWords + groupWords > 500 && currentWords >= 300) {
      chunks.push(current.join('\n\n'));
      current = [group]; currentWords = groupWords;
    } else {
      current.push(group); currentWords += groupWords;
    }
  }
  if (current.length > 0) {
    if (currentWords < 150 && chunks.length > 0) chunks[chunks.length - 1] += '\n\n' + current.join('\n\n');
    else chunks.push(current.join('\n\n'));
  }
  return chunks.length > 0 ? chunks : [trimmed];
}

// ── XML output parsers (mirrors lib/parser.ts) ───────────────────────────────

function stripFences(raw) {
  let s = raw.trim();
  const m = s.match(/^```(?:[a-zA-Z]+)?\s*\n([\s\S]*?)\n\s*```\s*$/);
  if (m) s = m[1].trim();
  return s;
}

function extractSingleTag(source, tag, stage) {
  const open = `<${tag}>`;
  const close = `</${tag}>`;
  const firstOpen = source.indexOf(open);
  if (firstOpen === -1) throw new Error(`[${stage}] Missing <${tag}> opening tag`);
  const lastOpen = source.lastIndexOf(open);
  if (lastOpen !== firstOpen) throw new Error(`[${stage}] Multiple <${tag}> opening tags`);
  const closeIdx = source.indexOf(close, firstOpen + open.length);
  if (closeIdx === -1) throw new Error(`[${stage}] Missing </${tag}> closing tag`);
  const lastClose = source.lastIndexOf(close);
  if (lastClose !== closeIdx) throw new Error(`[${stage}] Multiple </${tag}> closing tags`);
  return source.slice(firstOpen + open.length, closeIdx).trim();
}

function parseTranslatorXml(raw) {
  if (typeof raw !== 'string') throw new Error('[translator] Empty or non-string output');
  const cleaned = stripFences(raw);
  if (!cleaned) throw new Error('[translator] Empty output');
  const translation = extractSingleTag(cleaned, 'translation', 'translator');
  if (!translation) throw new Error('[translator] Empty <translation> block');
  const flagsBlock = extractSingleTag(cleaned, 'flags', 'translator');
  const flags = [];
  const re = /<flag>([\s\S]*?)<\/flag>/g;
  let m;
  while ((m = re.exec(flagsBlock)) !== null) {
    const t = m[1].trim();
    if (t) flags.push(t);
  }
  return { translation, flags };
}

function parseSmootherXml(raw) {
  if (typeof raw !== 'string') throw new Error('[smoother] Empty or non-string output');
  const cleaned = stripFences(raw);
  if (!cleaned) throw new Error('[smoother] Empty output');
  const smoothed = extractSingleTag(cleaned, 'smoothed', 'smoother');
  if (!smoothed) throw new Error('[smoother] Empty <smoothed> block');
  return { smoothed };
}

// ── Agent functions ──────────────────────────────────────────────────────────

async function translatorAgent(chunk, chunkIndex, totalChunks) {
  const raw = await callClaude({
    model: SONNET, max_tokens: 8192,
    system: TRANSLATOR_SYSTEM,
    messages: [{ role: 'user', content: `Chunk ${chunkIndex + 1} of ${totalChunks}. Translate the following Gujarati text into English following the rules above. For verse or poetic lines, include the Roman transliteration in curly quotes first, then the English meaning in parentheses — both mandatory. Output ONLY the two XML blocks specified in the system prompt: <translation>…</translation><flags>…</flags>.\n\nGUJARATI:\n${chunk}` }],
  });
  return parseTranslatorXml(raw);
}

async function smootherAgent(text) {
  const raw = await callClaude({
    model: SONNET, max_tokens: 8192,
    system: SMOOTHER_SYSTEM,
    messages: [{ role: 'user', content: `Smooth the following passage per the rules above. Output ONLY <smoothed>…</smoothed>.\n\n${text}` }],
  });
  return parseSmootherXml(raw);
}

/**
 * @deprecated Admin-only telemetry. Off by default. Tolerant JSON parser
 * because the reviewer's score is best-effort and never blocks the user path.
 */
async function reviewerAgent(original, translation) {
  const fallback = { score: -1, certifiable: false };
  let raw;
  try {
    raw = await callClaude({
      model: SONNET, max_tokens: 16000,
      system: REVIEWER_SYSTEM,
      messages: [{ role: 'user', content: `GUJARATI SOURCE:\n${original}\n\nTRANSLATION TO AUDIT:\n${translation}` }],
    });
  } catch (err) {
    console.error('  [telemetry] Reviewer API call failed:', err.message);
    return fallback;
  }
  const stripped = raw.replace(/^```(?:json)?\s*/gm, '').replace(/\s*```$/gm, '');
  const match = stripped.match(/\{[\s\S]*\}/);
  if (!match) return fallback;
  const jsonStr = match[0];
  try {
    const p = JSON.parse(jsonStr);
    const rawScore = typeof p.totalScore === 'number' ? p.totalScore : (typeof p.score === 'number' ? p.score : -1);
    return {
      score: Math.max(-1, Math.min(100, rawScore)),
      certifiable: typeof p.certifiable === 'boolean' ? p.certifiable : false,
    };
  } catch {
    let score = -1;
    const tsm = jsonStr.match(/"totalScore"\s*:\s*(\d+)/);
    if (tsm) score = Math.max(0, Math.min(100, parseInt(tsm[1], 10)));
    return { score, certifiable: false };
  }
}

function assemblerAgent(smoothedChunks) {
  if (smoothedChunks.length <= 1) return smoothedChunks[0] ?? '';
  const result = [];
  for (let i = 0; i < smoothedChunks.length; i++) {
    const chunk = smoothedChunks[i].trim();
    if (!chunk) continue;
    if (result.length > 0) {
      const prevSentences = result[result.length - 1].split(/(?<=[.!?])\s+/).filter(Boolean);
      const currSentences = chunk.split(/(?<=[.!?])\s+/).filter(Boolean);
      let overlap = 0;
      for (let n = Math.min(2, prevSentences.length, currSentences.length); n >= 1; n--) {
        if (prevSentences.slice(-n).join(' ').trim() === currSentences.slice(0, n).join(' ').trim()) { overlap = n; break; }
      }
      result.push(overlap > 0 ? currSentences.slice(overlap).join(' ') : chunk);
    } else {
      result.push(chunk);
    }
  }
  return result.join('\n\n');
}

// ── Rules enforcer (simplified — full rules loaded via tsx above) ─────────────
// The full rulesEnforcerAgent is in pipeline.ts. We load it via tsx if possible.

let rulesEnforcerAgent;
try {
  const { execSync } = await import('node:child_process');
  // Export the function as a serialized module isn't practical,
  // so we apply basic rules inline. The full enforcer runs regex replacements.
  // For the worker, we'll do a simpler version that covers the essentials.
  rulesEnforcerAgent = (text) => {
    let t = text;
    // Curly quotes
    let openDouble = true;
    t = t.replace(/"/g, () => { const q = openDouble ? '\u201c' : '\u201d'; openDouble = !openDouble; return q; });
    t = t.replace(/'([^']{2,})'/g, '\u2018$1\u2019');
    // Em dash → spaced en dash
    t = t.replace(/\u2014/g, ' \u2013 ').replace(/ {2,}\u2013 {2,}/g, ' \u2013 ');
    // Clean up double spaces
    t = t.replace(/ {2,}/g, ' ').replace(/^ +/gm, '');
    return { text: t, corrections: [], totalFixes: 0 };
  };
} catch {
  rulesEnforcerAgent = (text) => ({ text, corrections: [], totalFixes: 0 });
}

// Try to load the real rules enforcer via tsx
try {
  const { execSync } = await import('node:child_process');
  const testResult = execSync(`npx tsx -e "import { rulesEnforcerAgent } from '${ROOT}/lib/pipeline.ts'; console.log('ok')"`, {
    encoding: 'utf-8', cwd: ROOT, maxBuffer: 1024 * 1024,
    env: { ...process.env, ...env },
  });
  if (testResult.trim() === 'ok') {
    // We can use tsx to run the enforcer. But since it's synchronous and we'd need
    // to shell out for each call, let's keep the inline version for performance.
    // The full rules are baked into the translator/reviewer system prompts anyway.
    console.log('[worker] Full rules enforcer available via tsx');
  }
} catch { /* inline version will be used */ }

// ── Run pipeline for a single job ────────────────────────────────────────────

async function runJobPipeline(jobId, jobData) {
  const { input } = jobData;
  const { text, chapterTitle, bookId, bookTitle, chapterIndex, totalChapters } = input;

  const reportProgress = async (update) => {
    const mergeDoc = {};
    if (update.status) mergeDoc.status = update.status;
    if (update.startedAt) mergeDoc.startedAt = update.startedAt;
    if (update.completedAt) mergeDoc.completedAt = update.completedAt;
    if (update.error) mergeDoc.error = update.error;
    if (update.result) mergeDoc.result = update.result;
    if (update.progress) {
      const existing = (await db.collection('jobs').doc(jobId).get()).data()?.progress ?? { currentStage: '', stages: {}, chunks: [] };
      const mergedStages = { ...existing.stages };
      if (update.progress.stages) {
        for (const [stage, stageData] of Object.entries(update.progress.stages)) {
          mergedStages[stage] = { ...(mergedStages[stage] ?? {}), ...stageData };
        }
      }
      const merged = {
        currentStage: update.progress.currentStage ?? existing.currentStage,
        stages: mergedStages,
        chunks: update.progress.chunks ?? existing.chunks,
      };
      if (update.progress.commentary) merged.commentary = update.progress.commentary;
      mergeDoc.progress = merged;
    }
    await db.collection('jobs').doc(jobId).set(mergeDoc, { merge: true });
  };

  // ── Stage 1: Chunker
  await reportProgress({ status: 'running', startedAt: new Date().toISOString(), progress: { currentStage: 'chunker', stages: { chunker: { status: 'running' } }, chunks: [] } });

  const chunks = deterministicChunk(text);
  if (chunks.length === 0) throw new Error('No content to translate');

  const chunkProgressArr = chunks.map((c, i) => ({ index: i, original: c.slice(0, 200) }));
  console.log(`  Chunked into ${chunks.length} pieces`);

  await reportProgress({ progress: { currentStage: 'translator', stages: { chunker: { status: 'done', chunkCount: chunks.length } }, chunks: chunkProgressArr } });

  // ── Stages 2-3: Pipelined per-chunk (translator → smoother)
  const translations = new Array(chunks.length).fill('');
  const chunkFlags = Array.from({ length: chunks.length }, () => []);
  const smoothedChunks = new Array(chunks.length).fill('');
  const reviewerTelemetry = []; // optional admin-only
  const chunkDataForStorage = [];

  let translateDone = 0, smoothDone = 0;

  function stageSnapshot() {
    return {
      chunker: { status: 'done', chunkCount: chunks.length },
      translator: { status: translateDone >= chunks.length ? 'done' : 'running', completed: translateDone, total: chunks.length },
      smoother: { status: smoothDone >= chunks.length ? 'done' : (smoothDone > 0 || translateDone > 0 ? 'running' : 'waiting'), completed: smoothDone, total: chunks.length },
    };
  }

  async function processChunk(i) {
    const chunkLabel = chunks.length === 1 ? '' : ` chunk ${i + 1}/${chunks.length}`;
    const srcWords = chunks[i].split(/\s+/).filter(Boolean).length;

    // Translate (XML output: <translation> + <flags>)
    await reportProgress({ progress: { currentStage: 'translator', commentary: `Translating${chunkLabel} (${srcWords} words) with full Aksharpith style context…`, stages: stageSnapshot(), chunks: chunkProgressArr } });
    console.log(`  [chunk ${i + 1}/${chunks.length}] Translating...`);
    const translatorOut = await translatorAgent(chunks[i], i, chunks.length);
    translations[i] = rulesEnforcerAgent(translatorOut.translation).text;
    chunkFlags[i] = translatorOut.flags;
    translateDone++;
    chunkProgressArr[i] = {
      ...chunkProgressArr[i],
      translation: translations[i].slice(0, 300),
      flags: translatorOut.flags,
    };
    const flagSummary = translatorOut.flags.length === 0
      ? 'no self-flags'
      : `${translatorOut.flags.length} self-flag${translatorOut.flags.length === 1 ? '' : 's'}`;
    await reportProgress({ progress: { currentStage: 'translator', commentary: `Translated${chunkLabel} — ${translations[i].split(/\s+/).filter(Boolean).length} words output, ${flagSummary}`, stages: stageSnapshot(), chunks: chunkProgressArr } });

    // Optional admin-only telemetry — fire-and-forget.
    if (ENABLE_REVIEWER_TELEMETRY) {
      reviewerTelemetry.push(
        reviewerAgent(chunks[i], translations[i])
          .then(r => ({ index: i, score: r.score, certifiable: r.certifiable }))
          .catch(err => {
            console.error(`  [telemetry] reviewer failed on chunk ${i}: ${err.message}`);
            return { index: i, score: -1, certifiable: false };
          }),
      );
    }

    // Smoother (XML output). Fall back to translator output on parser/model failure.
    await reportProgress({ progress: { currentStage: 'smoother', commentary: `Smoothing${chunkLabel} — preserving direct quotes, transliterated verses and proper nouns…`, stages: stageSnapshot(), chunks: chunkProgressArr } });
    console.log(`  [chunk ${i + 1}/${chunks.length}] Smoothing...`);
    let smoothedText = translations[i];
    let smootherFallback = false;
    try {
      const smoothed = await smootherAgent(translations[i]);
      smoothedText = smoothed.smoothed;
    } catch (err) {
      smootherFallback = true;
      console.warn(`  [chunk ${i + 1}/${chunks.length}] Smoother fallback: ${err.message}`);
    }
    smoothedChunks[i] = rulesEnforcerAgent(smoothedText).text;
    smoothDone++;
    await reportProgress({ progress: { currentStage: 'smoother', commentary: `Smoothed${chunkLabel}${smootherFallback ? ' (fell back to translator output)' : ''}`, stages: stageSnapshot(), chunks: chunkProgressArr } });

    chunkDataForStorage.push({
      index: i,
      originalGujarati: chunks[i],
      translation: smoothedChunks[i],
      flags: translatorOut.flags,
    });
  }

  // Process in batches
  const allChunkIndices = Array.from({ length: chunks.length }, (_, i) => i);
  for (let start = 0; start < allChunkIndices.length; start += BATCH) {
    const batch = allChunkIndices.slice(start, start + BATCH);
    const results = await Promise.allSettled(batch.map(i => processChunk(i)));
    const firstFailure = results.find(r => r.status === 'rejected');
    if (firstFailure && firstFailure.status === 'rejected') throw firstFailure.reason;

    const currentStage = smoothDone === chunks.length
      ? 'assembler'
      : translateDone > 0 ? 'smoother' : 'translator';
    await reportProgress({
      progress: { currentStage, stages: stageSnapshot(), chunks: chunkProgressArr },
    });
  }

  // ── Stage 4: Assembler (deterministic)
  await reportProgress({ progress: { currentStage: 'assembler', commentary: `Joining ${chunks.length} chunks into a single document — deduplicating boundary overlaps…`, stages: { assembler: { status: 'running' } }, chunks: chunkProgressArr } });
  const assembled = assemblerAgent(smoothedChunks);
  await reportProgress({ progress: { currentStage: 'enforcer', commentary: 'Document assembled successfully', stages: { assembler: { status: 'done' } }, chunks: chunkProgressArr } });

  // ── Stage 5: Rules Enforcer (deterministic)
  await reportProgress({ progress: { currentStage: 'enforcer', commentary: 'Running deterministic rules — terminology, punctuation, diacritics, place names…', stages: { enforcer: { status: 'running' } }, chunks: chunkProgressArr } });
  const enforced = rulesEnforcerAgent(assembled);
  const finalText = enforced.text;
  const finalWords = finalText.trim().split(/\s+/).filter(Boolean).length;
  const totalFlags = chunkFlags.reduce((s, f) => s + f.length, 0);

  // Resolve admin-only telemetry (already kicked off; this just awaits).
  let adminTelemetry;
  if (ENABLE_REVIEWER_TELEMETRY && reviewerTelemetry.length > 0) {
    const settled = await Promise.all(reviewerTelemetry);
    const valid = settled.filter(s => s.score >= 0);
    adminTelemetry = {
      reviewerScore: valid.length > 0 ? Math.round(valid.reduce((s, r) => s + r.score, 0) / valid.length) : 0,
      perChunk: settled.sort((a, b) => a.index - b.index),
    };
  }

  // Save translation document. Reviewer telemetry stored on the doc; user-facing
  // payload (below) does not include reviewer-derived fields.
  let translationId = '';
  try {
    const docRef = await db.collection('translations').add({
      uid: jobData.uid, email: jobData.email,
      chapterTitle: chapterTitle || null, bookId: bookId || null, bookTitle: bookTitle || null,
      chapterIndex: chapterIndex ?? null, totalChapters: totalChapters ?? null,
      inputWordCount: input.wordCount, outputWordCount: finalWords,
      output: finalText,
      inputPreview: text.slice(0, 300),
      chunkData: chunkDataForStorage.sort((a, b) => a.index - b.index),
      flagsCount: totalFlags,
      adminTelemetry: adminTelemetry ?? null,
      createdAt: new Date().toISOString(),
    });
    translationId = docRef.id;
  } catch (err) {
    console.error('  Firestore save error:', err.message);
  }

  // Report completion. User-facing payload carries flags + final text only.
  await reportProgress({
    status: 'completed',
    completedAt: new Date().toISOString(),
    progress: {
      currentStage: 'enforcer',
      stages: { enforcer: { status: 'done', totalFixes: enforced.totalFixes } },
      chunks: chunkProgressArr,
    },
    result: {
      output: finalText,
      wordCount: finalWords,
      totalFixes: enforced.totalFixes,
      corrections: enforced.corrections.map(c => ({ from: c.from, to: c.to, rule: c.rule, count: c.count })),
      flagsCount: totalFlags,
      translationId,
    },
  });
}

// ── Poll loop ────────────────────────────────────────────────────────────────

let processing = false;

async function pollForJobs() {
  if (processing) return;

  try {
    // Query by status only (auto-indexed) and filter mode in code
    // to avoid needing a composite Firestore index
    const snapshot = await db.collection('jobs')
      .where('status', '==', 'pending')
      .limit(10)
      .get();

    if (snapshot.empty) return;

    // Find the oldest local job
    const localDocs = snapshot.docs
      .filter(d => d.data().mode === 'local')
      .sort((a, b) => (a.data().createdAt ?? '').localeCompare(b.data().createdAt ?? ''));

    if (localDocs.length === 0) return;

    processing = true;
    const doc = localDocs[0];
    const jobId = doc.id;
    const jobData = doc.data();

    console.log(`\n[worker] Picked up job ${jobId} (${jobData.input?.wordCount ?? '?'} words)`);

    try {
      await runJobPipeline(jobId, jobData);
      console.log(`[worker] Job ${jobId} completed successfully`);
    } catch (err) {
      console.error(`[worker] Job ${jobId} failed:`, err.message);
      await db.collection('jobs').doc(jobId).set({
        status: 'failed',
        error: err.message || 'Unknown error',
        completedAt: new Date().toISOString(),
      }, { merge: true });
    } finally {
      processing = false;
    }
  } catch (err) {
    console.error('[worker] Poll error:', err.message);
  }
}

// ── PDF extraction for large files ───────────────────────────────────────────

async function pollForExtractions() {
  if (processing) return;

  try {
    const snapshot = await db.collection('extractions')
      .where('status', '==', 'pending')
      .limit(1)
      .get();

    if (snapshot.empty) return;

    processing = true;
    const doc = snapshot.docs[0];
    const extractionId = doc.id;
    const data = doc.data();

    console.log(`\n[worker] Extracting PDF: ${data.filename} (${data.pages} pages, ${(data.fileSizeBytes / 1024 / 1024).toFixed(1)} MB)`);

    try {
      await db.collection('extractions').doc(extractionId).set({
        status: 'running',
        progress: 'Splitting PDF into page chunks...',
      }, { merge: true });

      const { readFileSync } = await import('node:fs');
      const buf = data.filePath ? readFileSync(data.filePath) : Buffer.from(data.fileBase64 || '', 'base64');
      const pages = data.pages || 1;

      // Split into chunks of ~20 pages
      const { PDFDocument } = await import('pdf-lib');
      const srcDoc = await PDFDocument.load(buf);
      const totalPages = srcDoc.getPageCount();
      const pagesPerChunk = Math.min(20, totalPages);
      const chunks = [];

      for (let start = 0; start < totalPages; start += pagesPerChunk) {
        const end = Math.min(start + pagesPerChunk, totalPages);
        const newDoc = await PDFDocument.create();
        const copiedPages = await newDoc.copyPages(srcDoc, Array.from({ length: end - start }, (_, i) => start + i));
        for (const p of copiedPages) newDoc.addPage(p);
        const bytes = await newDoc.save();
        chunks.push(Buffer.from(bytes));
      }

      console.log(`  Split into ${chunks.length} chunks of ~${pagesPerChunk} pages`);

      // Extract text from each chunk via Claude
      const PDF_PROMPT = `Extract ALL text from this PDF document exactly as written. Preserve:
- Every paragraph (blank line between paragraphs)
- All Gujarati Unicode text exactly as it appears
- All numbers, dates, names, verses
- Chapter/section headings (mark as "=== CHAPTER: <title> ===" on its own line)
- Verse/kirtan lines on separate lines
Return ONLY the extracted text — no commentary, no notes, no preamble.`;

      const parts = [];
      for (let i = 0; i < chunks.length; i++) {
        await db.collection('extractions').doc(extractionId).set({
          progress: `Extracting text from pages ${i * pagesPerChunk + 1}–${Math.min((i + 1) * pagesPerChunk, totalPages)} of ${totalPages}...`,
        }, { merge: true });

        console.log(`  Extracting chunk ${i + 1}/${chunks.length}...`);
        // Write PDF chunk to temp file for claude CLI to read
        const { writeFileSync, unlinkSync } = await import('node:fs');
        const { tmpdir } = await import('node:os');
        const tmpPath = `${tmpdir()}/aksharpith-extract-${i}.pdf`;
        writeFileSync(tmpPath, chunks[i]);
        try {
          const text = await callClaude({
            model: 'claude-haiku-4-5-20251001',
            max_tokens: 16000,
            system: 'You are a document text extractor. Extract all text faithfully.',
            messages: [{ role: 'user', content: `${PDF_PROMPT}\n\nThe PDF file is at: ${tmpPath}\nRead and extract ALL text from it.` }],
          });
          parts.push(text);
        } finally {
          try { unlinkSync(tmpPath); } catch { /* ok */ }
        }
      }

      const fullText = parts.join('\n\n');
      const wordCount = fullText.trim().split(/\s+/).filter(Boolean).length;

      // Detect chapters
      const lines = fullText.split('\n');
      const chapterPattern = /^===\s*CHAPTER:\s*(.+?)\s*===$/i;
      const chapters = [];
      for (let i = 0; i < lines.length; i++) {
        const m = lines[i].trim().match(chapterPattern);
        if (m) chapters.push({ title: m[1], startLine: i });
      }

      await db.collection('extractions').doc(extractionId).set({
        status: 'completed',
        text: fullText,
        wordCount,
        chapters: chapters.length > 1 ? chapters : null,
        progress: `Extracted ${wordCount.toLocaleString()} words from ${totalPages} pages`,
      }, { merge: true });

      // Clean up the source file and Firestore data
      if (data.filePath) {
        try { const { unlinkSync } = await import('node:fs'); unlinkSync(data.filePath); } catch { /* ok */ }
      }
      await db.collection('extractions').doc(extractionId).update({
        fileBase64: '', filePath: '',
      });

      console.log(`[worker] Extraction complete: ${wordCount} words, ${chapters.length} chapters`);
    } catch (err) {
      console.error(`[worker] Extraction failed:`, err.message);
      await db.collection('extractions').doc(extractionId).set({
        status: 'failed',
        error: err.message || 'Extraction failed',
      }, { merge: true });
    } finally {
      processing = false;
    }
  } catch (err) {
    console.error('[worker] Extraction poll error:', err.message);
  }
}

// ── Start ────────────────────────────────────────────────────────────────────

console.log('[worker] Aksharpith local worker started (using claude CLI — Max subscription)');
console.log(`[worker] Polling Firestore every ${POLL_INTERVAL / 1000}s for jobs + extractions...`);

// Initial poll
pollForJobs();

// Continuous polling — alternate between jobs and extractions
let pollCycle = 0;
setInterval(() => {
  if (pollCycle % 2 === 0) pollForJobs();
  else pollForExtractions();
  pollCycle++;
}, POLL_INTERVAL);

// Keep process alive
process.on('SIGINT', () => {
  console.log('\n[worker] Shutting down...');
  process.exit(0);
});
process.on('SIGTERM', () => {
  console.log('\n[worker] Shutting down...');
  process.exit(0);
});
