#!/usr/bin/env node
/**
 * Local Worker — watches Firestore for jobs with mode:'local', runs them locally.
 * No timeout constraints. Starts automatically via launchd or alongside dev server.
 *
 * Usage: node scripts/local-worker.mjs
 * Reads env from .env.local + .env.vercel.local
 */

import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import https from 'node:https';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

// ── Load env ─────────────────────────────────────────────────────────────────

function loadEnvFile(path) {
  if (!existsSync(path)) return {};
  const vars = {};
  for (const line of readFileSync(path, 'utf-8').split('\n')) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=["']?([\s\S]*?)["']?\s*$/);
    if (m) vars[m[1]] = m[2];
  }
  return vars;
}

const env = {
  ...loadEnvFile(resolve(ROOT, '.env.local')),
  ...loadEnvFile(resolve(ROOT, '.env.vercel.local')),
};

// The Claude Agent SDK reads CLAUDE_CODE_OAUTH_TOKEN from process.env directly,
// so promote it across from the .env.local-loaded `env` map.
if (env.CLAUDE_CODE_OAUTH_TOKEN && !process.env.CLAUDE_CODE_OAUTH_TOKEN) {
  process.env.CLAUDE_CODE_OAUTH_TOKEN = env.CLAUDE_CODE_OAUTH_TOKEN;
}

// API key no longer required — worker uses claude CLI (Max subscription)
const API_KEY = env.ANTHROPIC_API_KEY?.trim() ?? '';

const PROJECT_ID = env.FIREBASE_PROJECT_ID || 'aksharpith-translator';
const CLIENT_EMAIL = env.FIREBASE_CLIENT_EMAIL;
const PRIVATE_KEY = env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, '\n');

if (!CLIENT_EMAIL || !PRIVATE_KEY) {
  console.error('Missing FIREBASE_CLIENT_EMAIL or FIREBASE_PRIVATE_KEY');
  process.exit(1);
}

// ── Firebase Admin ───────────────────────────────────────────────────────────

import { initializeApp, cert, getApps } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';

if (getApps().length === 0) {
  initializeApp({ credential: cert({ projectId: PROJECT_ID, clientEmail: CLIENT_EMAIL, privateKey: PRIVATE_KEY }) });
}
const db = getFirestore();

// ── Pipeline config ──────────────────────────────────────────────────────────

const SONNET = 'claude-sonnet-4-20250514';
const BATCH = 5;
const POLL_INTERVAL = 5_000;
const SDK_MAX_RETRIES = 2;
const SDK_RETRY_DELAY_MS = 5_000;

// ── Load rules + prompts via tsx ─────────────────────────────────────────────
// Translator and smoother system prompts built from the TypeScript rules module.

let rulesModule;
try {
  const { execSync } = await import('node:child_process');
  // Single-line eval to keep tsx/esbuild from interpreting \n as a TS source escape.
  const rulesScript = `import { buildTranslatorSystem, buildSmootherSystem } from '${ROOT}/lib/rules/index.ts'; console.log(JSON.stringify({ TRANSLATOR_SYSTEM: buildTranslatorSystem(), SMOOTHER_SYSTEM: buildSmootherSystem() }));`;
  const result = execSync(`npx tsx -e ${JSON.stringify(rulesScript)}`, {
    encoding: 'utf-8', cwd: ROOT, maxBuffer: 5 * 1024 * 1024,
    env: { ...process.env, ...env },
  });
  rulesModule = JSON.parse(result.trim());
} catch (e) {
  console.error('Failed to load rules via tsx. Falling back to inline prompts.');
  console.error(e.message);
  rulesModule = {
    TRANSLATOR_SYSTEM: 'You are a trustee of the parampara. Translate Gujarati to English with fidelity to BAPS Swaminarayan editorial rules. Output ONLY <translation>...</translation><flags>...</flags>.',
    SMOOTHER_SYSTEM: 'I am working on improving a translation of a non-fiction historical biography for better readability. Keep direct quotes, transliterated verses and proper nouns verbatim. Output ONLY <smoothed>...</smoothed>.',
  };
}

const { TRANSLATOR_SYSTEM, SMOOTHER_SYSTEM } = rulesModule;

// ── Claude Agent SDK ─────────────────────────────────────────────────────────
// Auth is via CLAUDE_CODE_OAUTH_TOKEN env var (loaded from .env.local at top of
// this file). Generated by `claude setup-token` — 1-year lifetime.
//
// Why SDK and not the raw `claude` CLI?
//   The CLI is the agentic IDE shell. Even with `-p`, it loads hooks/LSP/MCP/
//   plugins/CLAUDE.md auto-discovery and runs the agent loop. Under non-trivial
//   prompts it opens 19+ TCP connections and hangs at the 5-min Node timeout.
//   The SDK calls Anthropic directly — clean HTTP, no agent overhead.
//
// We disable all built-in tools and cap maxTurns at 1 so query() acts as a
// pure system+user → text completion — no Read/Edit/Bash/Grep, no agent loop.

import { query } from '@anthropic-ai/claude-agent-sdk';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';

if (!process.env.CLAUDE_CODE_OAUTH_TOKEN) {
  console.error('Missing CLAUDE_CODE_OAUTH_TOKEN. Run `claude setup-token` and add to .env.local.');
  process.exit(1);
}

// Isolated cwd keeps the SDK from auto-discovering workspace CLAUDE.md / .claude/.
const SDK_CWD = mkdtempSync(`${tmpdir()}/aksharpith-sdk-`);

async function callClaudeOnce(params) {
  const userPrompt = params.messages.map(m => typeof m.content === 'string' ? m.content : '').join('\n');

  const q = query({
    prompt: userPrompt,
    options: {
      systemPrompt: params.system,
      model: params.model,
      tools: [],                       // pure text completion — no Read/Edit/Bash/etc.
      maxTurns: 1,                     // single response, no agent loop
      cwd: SDK_CWD,
      permissionMode: 'bypassPermissions',
    },
  });

  let text = '';
  let errorKind = null;
  for await (const msg of q) {
    if (msg.type === 'assistant') {
      if (msg.error) errorKind = msg.error;
      for (const block of msg.message.content ?? []) {
        if (block.type === 'text' && typeof block.text === 'string') text += block.text;
      }
    } else if (msg.type === 'result' && msg.subtype !== 'success') {
      errorKind = errorKind ?? msg.subtype;
    }
  }

  if (errorKind) throw new Error(`Claude SDK error: ${errorKind}`);
  if (!text.trim()) throw new Error('Empty response from Claude SDK');
  return text;
}

async function callClaude(params) {
  let lastErr;
  for (let attempt = 0; attempt <= SDK_MAX_RETRIES; attempt++) {
    try {
      return await callClaudeOnce(params);
    } catch (err) {
      lastErr = err;
      console.error(`  [callClaude] attempt ${attempt + 1}/${SDK_MAX_RETRIES + 1} failed: ${err.message}`);
      if (attempt < SDK_MAX_RETRIES) {
        await new Promise(r => setTimeout(r, SDK_RETRY_DELAY_MS * (attempt + 1)));
      }
    }
  }
  throw lastErr;
}

// ── Chunker ──────────────────────────────────────────────────────────────────

function isVerseBlock(para) {
  const lines = para.split('\n').map(l => l.trim()).filter(Boolean);
  if (lines.length < 2) return false;
  const quotedVerse = lines.some(l => /^[\u201c\u201d"'\u2018\u2019]/.test(l) && /[āīūṛṅñṭḍṇśṣḥ]/.test(l));
  const avgLen = lines.reduce((s, l) => s + l.length, 0) / lines.length;
  const similarLength = lines.length >= 2 && lines.every(l => Math.abs(l.length - avgLen) < avgLen * 0.5);
  const diacriticLines = lines.filter(l => /[āīūṛṅñṭḍṇśṣḥ]/.test(l)).length;
  const mostlyDiacritic = diacriticLines >= lines.length * 0.5;
  return quotedVerse || (similarLength && mostlyDiacritic);
}

function deterministicChunk(text) {
  const trimmed = text.trim();
  if (!trimmed) return [];
  const totalWords = trimmed.split(/\s+/).filter(Boolean).length;
  if (totalWords <= 500) return [trimmed];

  let rawParagraphs = trimmed.split(/\n\s*\n/);
  const hasGiantPara = rawParagraphs.some(p => p.trim().split(/\s+/).length > 500);
  if (hasGiantPara) rawParagraphs = trimmed.split(/\n/).filter(l => l.trim());

  const groups = [];
  let pendingVerse = null;
  for (const para of rawParagraphs) {
    const p = para.trim();
    if (!p) continue;
    if (isVerseBlock(p)) {
      if (groups.length > 0) groups[groups.length - 1] += '\n\n' + p;
      else pendingVerse = pendingVerse ? pendingVerse + '\n\n' + p : p;
    } else {
      if (pendingVerse) { groups.push(pendingVerse + '\n\n' + p); pendingVerse = null; }
      else groups.push(p);
    }
  }
  if (pendingVerse) groups.push(pendingVerse);

  const chunks = [];
  let current = [], currentWords = 0;
  for (const group of groups) {
    const groupWords = group.split(/\s+/).length;
    if (currentWords + groupWords > 500 && currentWords >= 300) {
      chunks.push(current.join('\n\n'));
      current = [group]; currentWords = groupWords;
    } else {
      current.push(group); currentWords += groupWords;
    }
  }
  if (current.length > 0) {
    if (currentWords < 150 && chunks.length > 0) chunks[chunks.length - 1] += '\n\n' + current.join('\n\n');
    else chunks.push(current.join('\n\n'));
  }
  return chunks.length > 0 ? chunks : [trimmed];
}

// ── XML output parsers (mirrors lib/parser.ts) ───────────────────────────────

function stripFences(raw) {
  let s = raw.trim();
  const m = s.match(/^```(?:[a-zA-Z]+)?\s*\n([\s\S]*?)\n\s*```\s*$/);
  if (m) s = m[1].trim();
  return s;
}

function extractSingleTag(source, tag, stage) {
  const open = `<${tag}>`;
  const close = `</${tag}>`;
  const firstOpen = source.indexOf(open);
  if (firstOpen === -1) throw new Error(`[${stage}] Missing <${tag}> opening tag`);
  const lastOpen = source.lastIndexOf(open);
  if (lastOpen !== firstOpen) throw new Error(`[${stage}] Multiple <${tag}> opening tags`);
  const closeIdx = source.indexOf(close, firstOpen + open.length);
  if (closeIdx === -1) throw new Error(`[${stage}] Missing </${tag}> closing tag`);
  const lastClose = source.lastIndexOf(close);
  if (lastClose !== closeIdx) throw new Error(`[${stage}] Multiple </${tag}> closing tags`);
  return source.slice(firstOpen + open.length, closeIdx).trim();
}

function parseTranslatorXml(raw) {
  if (typeof raw !== 'string') throw new Error('[translator] Empty or non-string output');
  const cleaned = stripFences(raw);
  if (!cleaned) throw new Error('[translator] Empty output');
  const translation = extractSingleTag(cleaned, 'translation', 'translator');
  if (!translation) throw new Error('[translator] Empty <translation> block');
  const flagsBlock = extractSingleTag(cleaned, 'flags', 'translator');
  const flags = [];
  const re = /<flag>([\s\S]*?)<\/flag>/g;
  let m;
  while ((m = re.exec(flagsBlock)) !== null) {
    const t = m[1].trim();
    if (t) flags.push(t);
  }
  return { translation, flags };
}

function parseSmootherXml(raw) {
  if (typeof raw !== 'string') throw new Error('[smoother] Empty or non-string output');
  const cleaned = stripFences(raw);
  if (!cleaned) throw new Error('[smoother] Empty output');
  const smoothed = extractSingleTag(cleaned, 'smoothed', 'smoother');
  if (!smoothed) throw new Error('[smoother] Empty <smoothed> block');
  return { smoothed };
}

// ── Agent functions ──────────────────────────────────────────────────────────

async function translatorAgent(chunk, chunkIndex, totalChunks) {
  const raw = await callClaude({
    model: SONNET, max_tokens: 8192,
    system: TRANSLATOR_SYSTEM,
    messages: [{ role: 'user', content: `Chunk ${chunkIndex + 1} of ${totalChunks}. Translate the following Gujarati text into English following the rules above. For verse or poetic lines, include the Roman transliteration in curly quotes first, then the English meaning in parentheses — both mandatory. Output ONLY the two XML blocks specified in the system prompt: <translation>…</translation><flags>…</flags>.\n\nGUJARATI:\n${chunk}` }],
  });
  return parseTranslatorXml(raw);
}

async function smootherAgent(text) {
  const raw = await callClaude({
    model: SONNET, max_tokens: 8192,
    system: SMOOTHER_SYSTEM,
    messages: [{ role: 'user', content: `Smooth the following passage per the rules above. Output ONLY <smoothed>…</smoothed>.\n\n${text}` }],
  });
  return parseSmootherXml(raw);
}

// Defensive: if the smoother stripped macrons (ā) from verse transliterations,
// restore the original line from the translator output. Mirrors the
// preserveMacrons helper in lib/pipeline.ts.
function preserveMacrons(translatorText, smootherText) {
  const MACRON = /[Āā]/g;
  const stripMacron = (s) => s.replace(/Ā/g, 'A').replace(/ā/g, 'a');
  const tCount = (translatorText.match(MACRON) ?? []).length;
  const sCount = (smootherText.match(MACRON) ?? []).length;
  if (tCount === 0 || sCount >= tCount) return { text: smootherText, restored: 0 };
  const verseLines = translatorText.split('\n').filter(l => /[Āā]/.test(l));
  let patched = smootherText;
  let restored = 0;
  for (const verseLine of verseLines) {
    if (patched.includes(verseLine)) continue;
    const stripped = stripMacron(verseLine);
    if (patched.includes(stripped)) {
      patched = patched.replace(stripped, verseLine);
      restored += (verseLine.match(MACRON) ?? []).length;
    }
  }
  return { text: patched, restored };
}

function assemblerAgent(smoothedChunks) {
  if (smoothedChunks.length <= 1) return smoothedChunks[0] ?? '';
  const result = [];
  for (let i = 0; i < smoothedChunks.length; i++) {
    const chunk = smoothedChunks[i].trim();
    if (!chunk) continue;
    if (result.length > 0) {
      const prevSentences = result[result.length - 1].split(/(?<=[.!?])\s+/).filter(Boolean);
      const currSentences = chunk.split(/(?<=[.!?])\s+/).filter(Boolean);
      let overlap = 0;
      for (let n = Math.min(2, prevSentences.length, currSentences.length); n >= 1; n--) {
        if (prevSentences.slice(-n).join(' ').trim() === currSentences.slice(0, n).join(' ').trim()) { overlap = n; break; }
      }
      result.push(overlap > 0 ? currSentences.slice(overlap).join(' ') : chunk);
    } else {
      result.push(chunk);
    }
  }
  return result.join('\n\n');
}

// ── Rules enforcer (simplified — full rules loaded via tsx above) ─────────────
// The full rulesEnforcerAgent is in pipeline.ts. We load it via tsx if possible.

let rulesEnforcerAgent;
try {
  const { execSync } = await import('node:child_process');
  // Export the function as a serialized module isn't practical,
  // so we apply basic rules inline. The full enforcer runs regex replacements.
  // For the worker, we'll do a simpler version that covers the essentials.
  rulesEnforcerAgent = (text) => {
    let t = text;
    // Curly quotes
    let openDouble = true;
    t = t.replace(/"/g, () => { const q = openDouble ? '\u201c' : '\u201d'; openDouble = !openDouble; return q; });
    t = t.replace(/'([^']{2,})'/g, '\u2018$1\u2019');
    // Em dash → spaced en dash
    t = t.replace(/\u2014/g, ' \u2013 ').replace(/ {2,}\u2013 {2,}/g, ' \u2013 ');
    // Clean up double spaces
    t = t.replace(/ {2,}/g, ' ').replace(/^ +/gm, '');
    return { text: t, corrections: [], totalFixes: 0 };
  };
} catch {
  rulesEnforcerAgent = (text) => ({ text, corrections: [], totalFixes: 0 });
}

// Try to load the real rules enforcer via tsx
try {
  const { execSync } = await import('node:child_process');
  const testResult = execSync(`npx tsx -e "import { rulesEnforcerAgent } from '${ROOT}/lib/pipeline.ts'; console.log('ok')"`, {
    encoding: 'utf-8', cwd: ROOT, maxBuffer: 1024 * 1024,
    env: { ...process.env, ...env },
  });
  if (testResult.trim() === 'ok') {
    // We can use tsx to run the enforcer. But since it's synchronous and we'd need
    // to shell out for each call, let's keep the inline version for performance.
    // The full rules are baked into the translator/smoother system prompts anyway.
    console.log('[worker] Full rules enforcer available via tsx');
  }
} catch { /* inline version will be used */ }

// ── Run pipeline for a single job ────────────────────────────────────────────

async function runJobPipeline(jobId, jobData) {
  const { input } = jobData;
  const { text, chapterTitle, bookId, bookTitle, chapterIndex, totalChapters } = input;

  const reportProgress = async (update) => {
    const mergeDoc = {};
    if (update.status) mergeDoc.status = update.status;
    if (update.startedAt) mergeDoc.startedAt = update.startedAt;
    if (update.completedAt) mergeDoc.completedAt = update.completedAt;
    if (update.error) mergeDoc.error = update.error;
    if (update.result) mergeDoc.result = update.result;
    if (update.progress) {
      const existing = (await db.collection('jobs').doc(jobId).get()).data()?.progress ?? { currentStage: '', stages: {}, chunks: [] };
      const mergedStages = { ...existing.stages };
      if (update.progress.stages) {
        for (const [stage, stageData] of Object.entries(update.progress.stages)) {
          mergedStages[stage] = { ...(mergedStages[stage] ?? {}), ...stageData };
        }
      }
      const merged = {
        currentStage: update.progress.currentStage ?? existing.currentStage,
        stages: mergedStages,
        chunks: update.progress.chunks ?? existing.chunks,
      };
      if (update.progress.commentary) merged.commentary = update.progress.commentary;
      mergeDoc.progress = merged;
    }
    await db.collection('jobs').doc(jobId).set(mergeDoc, { merge: true });
  };

  // ── Stage 1: Chunker
  await reportProgress({ status: 'running', startedAt: new Date().toISOString(), progress: { currentStage: 'chunker', stages: { chunker: { status: 'running' } }, chunks: [] } });

  const chunks = deterministicChunk(text);
  if (chunks.length === 0) throw new Error('No content to translate');

  const chunkProgressArr = chunks.map((c, i) => ({ index: i, original: c.slice(0, 200) }));
  console.log(`  Chunked into ${chunks.length} pieces`);

  await reportProgress({ progress: { currentStage: 'translator', stages: { chunker: { status: 'done', chunkCount: chunks.length } }, chunks: chunkProgressArr } });

  // ── Stages 2-3: Pipelined per-chunk (translator → enforcer → smoother → enforcer)
  const translations = new Array(chunks.length).fill('');
  const chunkFlags = Array.from({ length: chunks.length }, () => []);
  const smoothedChunks = new Array(chunks.length).fill('');
  const chunkDataForStorage = [];

  let translateDone = 0, smoothDone = 0;

  function stageSnapshot() {
    return {
      chunker: { status: 'done', chunkCount: chunks.length },
      translator: { status: translateDone >= chunks.length ? 'done' : 'running', completed: translateDone, total: chunks.length },
      smoother: { status: smoothDone >= chunks.length ? 'done' : (smoothDone > 0 || translateDone > 0 ? 'running' : 'waiting'), completed: smoothDone, total: chunks.length },
    };
  }

  async function processChunk(i) {
    const chunkLabel = chunks.length === 1 ? '' : ` chunk ${i + 1}/${chunks.length}`;
    const srcWords = chunks[i].split(/\s+/).filter(Boolean).length;

    // Translate (XML output: <translation> + <flags>)
    await reportProgress({ progress: { currentStage: 'translator', commentary: `Translating${chunkLabel} (${srcWords} words) with full Aksharpith style context…`, stages: stageSnapshot(), chunks: chunkProgressArr } });
    console.log(`  [chunk ${i + 1}/${chunks.length}] Translating...`);
    const translatorOut = await translatorAgent(chunks[i], i, chunks.length);
    translations[i] = rulesEnforcerAgent(translatorOut.translation).text;
    chunkFlags[i] = translatorOut.flags;
    translateDone++;
    chunkProgressArr[i] = {
      ...chunkProgressArr[i],
      translation: translations[i].slice(0, 300),
      flags: translatorOut.flags,
    };
    const flagSummary = translatorOut.flags.length === 0
      ? 'no self-flags'
      : `${translatorOut.flags.length} self-flag${translatorOut.flags.length === 1 ? '' : 's'}`;
    await reportProgress({ progress: { currentStage: 'translator', commentary: `Translated${chunkLabel} — ${translations[i].split(/\s+/).filter(Boolean).length} words output, ${flagSummary}`, stages: stageSnapshot(), chunks: chunkProgressArr } });

    // Smoother (XML output). Fall back to translator output on parser/model failure.
    await reportProgress({ progress: { currentStage: 'smoother', commentary: `Smoothing${chunkLabel} — preserving direct quotes, transliterated verses and proper nouns…`, stages: stageSnapshot(), chunks: chunkProgressArr } });
    console.log(`  [chunk ${i + 1}/${chunks.length}] Smoothing...`);
    let smoothedText = translations[i];
    let smootherFallback = false;
    try {
      const smoothed = await smootherAgent(translations[i]);
      smoothedText = smoothed.smoothed;
    } catch (err) {
      smootherFallback = true;
      console.warn(`  [chunk ${i + 1}/${chunks.length}] Smoother fallback: ${err.message}`);
    }

    // Defensive: restore any macrons the smoother stripped on verse lines.
    const { text: macronSafe, restored: macronsRestored } = preserveMacrons(translations[i], smoothedText);
    smoothedText = macronSafe;
    if (macronsRestored > 0) {
      const flag = `Smoother stripped ${macronsRestored} macron${macronsRestored === 1 ? '' : 's'} from verse transliteration${macronsRestored === 1 ? '' : 's'} — auto-restored from translator output.`;
      chunkFlags[i] = [...chunkFlags[i], flag];
      console.warn(`  [chunk ${i + 1}/${chunks.length}] ${flag}`);
    }

    smoothedChunks[i] = rulesEnforcerAgent(smoothedText).text;
    smoothDone++;
    chunkProgressArr[i] = { ...chunkProgressArr[i], flags: chunkFlags[i] };
    await reportProgress({ progress: { currentStage: 'smoother', commentary: `Smoothed${chunkLabel}${smootherFallback ? ' (fell back to translator output)' : ''}${macronsRestored > 0 ? ` — restored ${macronsRestored} macron${macronsRestored === 1 ? '' : 's'}` : ''}`, stages: stageSnapshot(), chunks: chunkProgressArr } });

    chunkDataForStorage.push({
      index: i,
      originalGujarati: chunks[i],
      translation: smoothedChunks[i],
      flags: chunkFlags[i],
    });
  }

  // Process in batches
  const allChunkIndices = Array.from({ length: chunks.length }, (_, i) => i);
  for (let start = 0; start < allChunkIndices.length; start += BATCH) {
    const batch = allChunkIndices.slice(start, start + BATCH);
    const results = await Promise.allSettled(batch.map(i => processChunk(i)));
    const firstFailure = results.find(r => r.status === 'rejected');
    if (firstFailure && firstFailure.status === 'rejected') throw firstFailure.reason;

    const currentStage = smoothDone === chunks.length
      ? 'assembler'
      : translateDone > 0 ? 'smoother' : 'translator';
    await reportProgress({
      progress: { currentStage, stages: stageSnapshot(), chunks: chunkProgressArr },
    });
  }

  // ── Stage 4: Assembler (deterministic)
  await reportProgress({ progress: { currentStage: 'assembler', commentary: `Joining ${chunks.length} chunks into a single document — deduplicating boundary overlaps…`, stages: { assembler: { status: 'running' } }, chunks: chunkProgressArr } });
  const assembled = assemblerAgent(smoothedChunks);
  await reportProgress({ progress: { currentStage: 'enforcer', commentary: 'Document assembled successfully', stages: { assembler: { status: 'done' } }, chunks: chunkProgressArr } });

  // ── Stage 5: Rules Enforcer (deterministic)
  await reportProgress({ progress: { currentStage: 'enforcer', commentary: 'Running deterministic rules — terminology, punctuation, diacritics, place names…', stages: { enforcer: { status: 'running' } }, chunks: chunkProgressArr } });
  const enforced = rulesEnforcerAgent(assembled);
  const finalText = enforced.text;
  const finalWords = finalText.trim().split(/\s+/).filter(Boolean).length;
  const totalFlags = chunkFlags.reduce((s, f) => s + f.length, 0);

  // Save translation document.
  let translationId = '';
  try {
    const docRef = await db.collection('translations').add({
      uid: jobData.uid, email: jobData.email,
      chapterTitle: chapterTitle || null, bookId: bookId || null, bookTitle: bookTitle || null,
      chapterIndex: chapterIndex ?? null, totalChapters: totalChapters ?? null,
      inputWordCount: input.wordCount, outputWordCount: finalWords,
      output: finalText,
      inputPreview: text.slice(0, 300),
      chunkData: chunkDataForStorage.sort((a, b) => a.index - b.index),
      flagsCount: totalFlags,
      createdAt: new Date().toISOString(),
    });
    translationId = docRef.id;
  } catch (err) {
    console.error('  Firestore save error:', err.message);
  }

  // Report completion. User-facing payload carries flags + final text only.
  await reportProgress({
    status: 'completed',
    completedAt: new Date().toISOString(),
    progress: {
      currentStage: 'enforcer',
      stages: { enforcer: { status: 'done', totalFixes: enforced.totalFixes } },
      chunks: chunkProgressArr,
    },
    result: {
      output: finalText,
      wordCount: finalWords,
      totalFixes: enforced.totalFixes,
      corrections: enforced.corrections.map(c => ({ from: c.from, to: c.to, rule: c.rule, count: c.count })),
      flagsCount: totalFlags,
      translationId,
    },
  });
}

// ── Poll loop ────────────────────────────────────────────────────────────────

let processing = false;

async function pollForJobs() {
  if (processing) return;

  try {
    // Query by status only (auto-indexed) and filter mode in code
    // to avoid needing a composite Firestore index
    const snapshot = await db.collection('jobs')
      .where('status', '==', 'pending')
      .limit(10)
      .get();

    if (snapshot.empty) return;

    // Find the oldest local job
    const localDocs = snapshot.docs
      .filter(d => d.data().mode === 'local')
      .sort((a, b) => (a.data().createdAt ?? '').localeCompare(b.data().createdAt ?? ''));

    if (localDocs.length === 0) return;

    processing = true;
    const doc = localDocs[0];
    const jobId = doc.id;
    const jobData = doc.data();

    console.log(`\n[worker] Picked up job ${jobId} (${jobData.input?.wordCount ?? '?'} words)`);

    try {
      await runJobPipeline(jobId, jobData);
      console.log(`[worker] Job ${jobId} completed successfully`);
    } catch (err) {
      console.error(`[worker] Job ${jobId} failed:`, err.message);
      await db.collection('jobs').doc(jobId).set({
        status: 'failed',
        error: err.message || 'Unknown error',
        completedAt: new Date().toISOString(),
      }, { merge: true });
    } finally {
      processing = false;
    }
  } catch (err) {
    console.error('[worker] Poll error:', err.message);
  }
}

// ── PDF extraction for large files ───────────────────────────────────────────

async function pollForExtractions() {
  if (processing) return;

  try {
    const snapshot = await db.collection('extractions')
      .where('status', '==', 'pending')
      .limit(1)
      .get();

    if (snapshot.empty) return;

    processing = true;
    const doc = snapshot.docs[0];
    const extractionId = doc.id;
    const data = doc.data();

    console.log(`\n[worker] Extracting PDF: ${data.filename} (${data.pages} pages, ${(data.fileSizeBytes / 1024 / 1024).toFixed(1)} MB)`);

    try {
      await db.collection('extractions').doc(extractionId).set({
        status: 'running',
        progress: 'Splitting PDF into page chunks...',
      }, { merge: true });

      const { readFileSync } = await import('node:fs');
      const buf = data.filePath ? readFileSync(data.filePath) : Buffer.from(data.fileBase64 || '', 'base64');
      const pages = data.pages || 1;

      // Split into chunks of ~20 pages
      const { PDFDocument } = await import('pdf-lib');
      const srcDoc = await PDFDocument.load(buf);
      const totalPages = srcDoc.getPageCount();
      const pagesPerChunk = Math.min(20, totalPages);
      const chunks = [];

      for (let start = 0; start < totalPages; start += pagesPerChunk) {
        const end = Math.min(start + pagesPerChunk, totalPages);
        const newDoc = await PDFDocument.create();
        const copiedPages = await newDoc.copyPages(srcDoc, Array.from({ length: end - start }, (_, i) => start + i));
        for (const p of copiedPages) newDoc.addPage(p);
        const bytes = await newDoc.save();
        chunks.push(Buffer.from(bytes));
      }

      console.log(`  Split into ${chunks.length} chunks of ~${pagesPerChunk} pages`);

      // Extract text from each chunk via Claude
      const PDF_PROMPT = `Extract ALL text from this PDF document exactly as written. Preserve:
- Every paragraph (blank line between paragraphs)
- All Gujarati Unicode text exactly as it appears
- All numbers, dates, names, verses
- Chapter/section headings (mark as "=== CHAPTER: <title> ===" on its own line)
- Verse/kirtan lines on separate lines
Return ONLY the extracted text — no commentary, no notes, no preamble.`;

      const parts = [];
      for (let i = 0; i < chunks.length; i++) {
        await db.collection('extractions').doc(extractionId).set({
          progress: `Extracting text from pages ${i * pagesPerChunk + 1}–${Math.min((i + 1) * pagesPerChunk, totalPages)} of ${totalPages}...`,
        }, { merge: true });

        console.log(`  Extracting chunk ${i + 1}/${chunks.length}...`);
        // Write PDF chunk to temp file for claude CLI to read
        const { writeFileSync, unlinkSync } = await import('node:fs');
        const { tmpdir } = await import('node:os');
        const tmpPath = `${tmpdir()}/aksharpith-extract-${i}.pdf`;
        writeFileSync(tmpPath, chunks[i]);
        try {
          const text = await callClaude({
            model: 'claude-haiku-4-5-20251001',
            max_tokens: 16000,
            system: 'You are a document text extractor. Extract all text faithfully.',
            messages: [{ role: 'user', content: `${PDF_PROMPT}\n\nThe PDF file is at: ${tmpPath}\nRead and extract ALL text from it.` }],
          });
          parts.push(text);
        } finally {
          try { unlinkSync(tmpPath); } catch { /* ok */ }
        }
      }

      const fullText = parts.join('\n\n');
      const wordCount = fullText.trim().split(/\s+/).filter(Boolean).length;

      // Detect chapters
      const lines = fullText.split('\n');
      const chapterPattern = /^===\s*CHAPTER:\s*(.+?)\s*===$/i;
      const chapters = [];
      for (let i = 0; i < lines.length; i++) {
        const m = lines[i].trim().match(chapterPattern);
        if (m) chapters.push({ title: m[1], startLine: i });
      }

      await db.collection('extractions').doc(extractionId).set({
        status: 'completed',
        text: fullText,
        wordCount,
        chapters: chapters.length > 1 ? chapters : null,
        progress: `Extracted ${wordCount.toLocaleString()} words from ${totalPages} pages`,
      }, { merge: true });

      // Clean up the source file and Firestore data
      if (data.filePath) {
        try { const { unlinkSync } = await import('node:fs'); unlinkSync(data.filePath); } catch { /* ok */ }
      }
      await db.collection('extractions').doc(extractionId).update({
        fileBase64: '', filePath: '',
      });

      console.log(`[worker] Extraction complete: ${wordCount} words, ${chapters.length} chapters`);
    } catch (err) {
      console.error(`[worker] Extraction failed:`, err.message);
      await db.collection('extractions').doc(extractionId).set({
        status: 'failed',
        error: err.message || 'Extraction failed',
      }, { merge: true });
    } finally {
      processing = false;
    }
  } catch (err) {
    console.error('[worker] Extraction poll error:', err.message);
  }
}

// ── Transliteration-first pipeline (page-by-page OCR) ───────────────────────
//
// New job system. Parent doc lives at `transliterationJobs/{jobId}` with N
// child page docs at `pages/{0001..N}`. This worker:
//   1. Claims one pending page at a time (serial for now; bump to 3-concurrent
//      in a follow-up once we've proven the OAuth path is stable).
//   2. Downloads the source PDF from Vercel Blob (cached per parent jobId so
//      we don't re-fetch for every page in a book).
//   3. Renders just that page to PNG via pdf-to-png-converter.
//   4. Calls the Agent SDK with an image content block to OCR Gujarati text.
//   5. Writes text back to the page doc and bumps parent.pagesCompleted.
//   6. When pagesCompleted === totalPages, transitions parent to assembling →
//      transliterating → done in pollForTransliterationJobs.

import { Buffer as NodeBuffer } from 'node:buffer';
import { randomUUID } from 'node:crypto';
import { writeFileSync, unlinkSync } from 'node:fs';
import { resolve as resolvePath } from 'node:path';
import { FieldValue } from 'firebase-admin/firestore';

const WORKER_ID = `worker-${process.pid}-${randomUUID().slice(0, 6)}`;
const STALE_CLAIM_MS = 10 * 60 * 1000; // 10 min — reaper unclaims pages held this long

// In-memory cache: jobId → Buffer of source PDF. Cleared once the parent
// transitions out of ocr_running. Each entry sized at the original PDF size
// (typically <30 MB) so this is bounded by concurrent jobs (1 for now).
const pdfCache = new Map();

// Lazy-load PROMPT for OCR — kept identical to translate-cli.mjs to match the
// established formatting contract from the Sethji smoke test.
const PAGE_OCR_PROMPT = `Extract ALL text from this image of a single PDF page exactly as written. This is a Gujarati text — preserve:
- All Gujarati Unicode text exactly as it appears
- All English text exactly
- All numbers, dates, names, verses
- Paragraph breaks and structure
- Any headings, bullet points, or numbered lists

Return ONLY the extracted text — no commentary, no notes, no preamble.`;

let transliteratorSystemPrompt = null;
async function getTransliteratorSystem() {
  if (transliteratorSystemPrompt) return transliteratorSystemPrompt;
  const { execSync } = await import('node:child_process');
  const script = `import { buildTransliteratorSystem } from '${ROOT}/lib/rules/transliterator-prompt.ts'; console.log(buildTransliteratorSystem());`;
  transliteratorSystemPrompt = execSync(`npx tsx -e ${JSON.stringify(script)}`, {
    encoding: 'utf-8', cwd: ROOT, maxBuffer: 5 * 1024 * 1024,
    env: { ...process.env, ...env },
  }).trim();
  return transliteratorSystemPrompt;
}

async function callClaudeWithImage(system, prompt, base64Png) {
  // The Agent SDK accepts AsyncIterable<SDKUserMessage> for content arrays.
  const userMessage = {
    type: 'user',
    message: {
      role: 'user',
      content: [
        { type: 'image', source: { type: 'base64', media_type: 'image/png', data: base64Png } },
        { type: 'text', text: prompt },
      ],
    },
    parent_tool_use_id: null,
    session_id: '',
  };
  const promptIter = (async function* () { yield userMessage; })();
  const q = query({
    prompt: promptIter,
    options: {
      systemPrompt: system,
      model: SONNET,
      tools: [],
      maxTurns: 1,
      cwd: SDK_CWD,
      permissionMode: 'bypassPermissions',
    },
  });
  let text = '';
  let errorKind = null;
  for await (const msg of q) {
    if (msg.type === 'assistant') {
      if (msg.error) errorKind = msg.error;
      for (const block of msg.message.content ?? []) {
        if (block.type === 'text' && typeof block.text === 'string') text += block.text;
      }
    } else if (msg.type === 'result' && msg.subtype !== 'success') {
      errorKind = errorKind ?? msg.subtype;
    }
  }
  if (errorKind) throw new Error(`Claude SDK error: ${errorKind}`);
  if (!text.trim()) throw new Error('Empty response from Claude SDK');
  return text;
}

async function getPdfBuffer(jobId, blobUrl) {
  const cached = pdfCache.get(jobId);
  if (cached) return cached;
  const res = await fetch(blobUrl);
  if (!res.ok) throw new Error(`Blob fetch ${res.status} for ${blobUrl}`);
  const buf = NodeBuffer.from(await res.arrayBuffer());
  pdfCache.set(jobId, buf);
  return buf;
}

async function renderPageToPng(pdfBuf, pageNum) {
  // pdfjs-based renderers (incl. pdf-to-png-converter) silently produce blank
  // PNGs for some scanner-output PDFs (Xerox AltaLink, etc.) — pdfjs can't
  // decode their font subsetting and emits a transparent canvas. Sonnet then
  // sees a blank image and OCR returns "I can't see any text" English instead
  // of Gujarati. Shell out to poppler's pdftoppm — much more compatible.
  // Requires `brew install poppler` on the worker host.
  const { execFile } = await import('node:child_process');
  const { promisify } = await import('node:util');
  const { readFileSync: rf } = await import('node:fs');
  const execFileP = promisify(execFile);

  const stamp = `${WORKER_ID}-${pageNum}-${Date.now()}`;
  const tmpPdf = resolvePath(tmpdir(), `aksharpith-${stamp}.pdf`);
  const outRoot = resolvePath(tmpdir(), `aksharpith-${stamp}-out`);
  writeFileSync(tmpPdf, pdfBuf);
  try {
    await execFileP('pdftoppm', [
      '-r', '200',            // ≈ 2x at typical 100 DPI source
      '-png',
      '-f', String(pageNum),
      '-l', String(pageNum),
      '-singlefile',          // emits exactly <outRoot>.png
      tmpPdf,
      outRoot,
    ]);
    const pngPath = `${outRoot}.png`;
    const pngBuf = rf(pngPath);
    try { unlinkSync(pngPath); } catch { /* ok */ }
    return pngBuf;
  } finally {
    try { unlinkSync(tmpPdf); } catch { /* ok */ }
  }
}

async function pollForPageJobs() {
  if (processing) return; // serialise with translation jobs for now
  try {
    // Find active parent jobs first. Avoids collectionGroup queries (which
    // need single-field index exemptions Firebase doesn't auto-create).
    // Fetch parents in pending or ocr_running state, then walk their pages
    // subcollections — those subcollection queries are auto-indexed because
    // their path is fully specified.
    const activeParents = [];
    for (const status of ['pending', 'ocr_running']) {
      const snap = await db.collection('transliterationJobs')
        .where('status', '==', status)
        .limit(5).get();
      activeParents.push(...snap.docs);
    }
    if (activeParents.length === 0) return;

    // Reaper: unclaim pages whose ocr_running claim has gone stale.
    const staleCutoff = new Date(Date.now() - STALE_CLAIM_MS).toISOString();
    for (const parent of activeParents) {
      const stale = await parent.ref.collection('pages')
        .where('status', '==', 'ocr_running')
        .limit(10).get();
      for (const doc of stale.docs) {
        const claimedAt = doc.data().claimedAt;
        if (claimedAt && claimedAt < staleCutoff) {
          await doc.ref.update({ status: 'pending', claimedBy: null, claimedAt: null });
          console.log(`[worker] Reaped stale claim on ${doc.ref.path}`);
        }
      }
    }

    // Pick a pending page across active parents. Order is unimportant —
    // pages are independent OCR units; the UI sorts by pageNum on render.
    // Skipping orderBy() avoids Firebase requiring a composite index on
    // (status, pageNum). Doc ID lexicographic order from the picker matches
    // pageNum order anyway because we pad pageNum with zeros at create time.
    let pageRef = null;
    let parentRef = null;
    for (const parent of activeParents) {
      const snap = await parent.ref.collection('pages')
        .where('status', '==', 'pending')
        .limit(1).get();
      if (!snap.empty) {
        pageRef = snap.docs[0].ref;
        parentRef = parent.ref;
        break;
      }
    }
    if (!pageRef || !parentRef) return;

    processing = true;

    // Claim via transaction. Firestore requires all reads before writes, so
    // we get both docs first, decide what to do, then write.
    const { pageNum, parent } = await db.runTransaction(async (tx) => {
      const [fresh, parentSnap] = await Promise.all([tx.get(pageRef), tx.get(parentRef)]);
      if (!fresh.exists || fresh.data().status !== 'pending') {
        throw new Error('Already claimed');
      }
      if ((fresh.data().attempts ?? 0) >= 3) {
        tx.update(pageRef, { status: 'ocr_failed' });
        throw new Error('Attempts exhausted');
      }
      const now = new Date().toISOString();
      tx.update(pageRef, {
        status: 'ocr_running',
        claimedBy: WORKER_ID,
        claimedAt: now,
        attempts: FieldValue.increment(1),
      });
      // First page claim flips parent from pending → ocr_running.
      if (parentSnap.exists && parentSnap.data().status === 'pending') {
        tx.update(parentRef, { status: 'ocr_running', startedAt: now });
      }
      return { pageNum: fresh.data().pageNum, parent: parentSnap.data() };
    }).catch((err) => {
      if (err.message === 'Already claimed' || err.message === 'Attempts exhausted') return null;
      throw err;
    });

    if (!pageNum) { processing = false; return; }

    console.log(`\n[worker] OCR page ${pageNum}/${parent.totalPages} of ${parent.filename}`);

    try {
      const pdfBuf = await getPdfBuffer(parentRef.id, parent.pdfBlobUrl);
      const pngBuf = await renderPageToPng(pdfBuf, pageNum);
      const text = await callClaudeWithImage(
        'You are an OCR engine. Extract text from images preserving all original formatting and language scripts (especially Gujarati).',
        PAGE_OCR_PROMPT,
        pngBuf.toString('base64'),
      );
      const cleaned = text.replace(/\r\n/g, '\n').replace(/\n{3,}/g, '\n\n').trim();
      const wordCount = cleaned.split(/\s+/).filter(Boolean).length;

      await pageRef.update({
        status: 'ocr_done',
        gujaratiText: cleaned,
        wordCount,
        completedAt: new Date().toISOString(),
        error: null,
      });
      await parentRef.update({ pagesCompleted: FieldValue.increment(1) });
      console.log(`  ✓ page ${pageNum} → ${wordCount} words`);
    } catch (err) {
      console.error(`  ✗ page ${pageNum} failed: ${err.message}`);
      // attempts was already incremented at claim time. Mark failed if cap hit.
      const fresh = await pageRef.get();
      const attempts = fresh.data()?.attempts ?? 3;
      await pageRef.update({
        status: attempts >= 3 ? 'ocr_failed' : 'pending',
        claimedBy: null,
        claimedAt: null,
        error: err.message?.slice(0, 500) ?? 'Unknown OCR error',
      });
      if (attempts >= 3) {
        await parentRef.update({
          status: 'failed',
          error: `Page ${pageNum} OCR failed after 3 attempts: ${err.message?.slice(0, 200)}`,
          completedAt: new Date().toISOString(),
        });
        pdfCache.delete(parentRef.id);
      }
    } finally {
      processing = false;
    }
  } catch (err) {
    console.error('[worker] Page-poll error:', err.message);
    processing = false;
  }
}

async function pollForTransliterationJobs() {
  if (processing) return;
  try {
    // Find a parent whose pages are all done but the transliterator hasn't
    // run yet. Status will be 'ocr_running' (set when first page was claimed).
    const ready = await db.collection('transliterationJobs')
      .where('status', '==', 'ocr_running')
      .limit(5).get();
    if (ready.empty) {
      // Also pick up jobs awaiting optional translation. Single-field query —
      // composite index not required. Filter the secondary condition client-
      // side from the small result set.
      const transReady = await db.collection('transliterationJobs')
        .where('translateRequested', '==', true)
        .limit(20).get();
      const candidate = transReady.docs.find(d => d.data().translationStatus === 'pending');
      if (!candidate) return;
      processing = true;
      try { await processTranslationStage(candidate); } finally { processing = false; }
      return;
    }

    // Find the first parent where pagesCompleted === totalPages.
    const candidate = ready.docs.find(d => {
      const data = d.data();
      return data.pagesCompleted >= data.totalPages;
    });
    if (!candidate) return;

    processing = true;
    try {
      await processTransliterationStage(candidate);
    } finally {
      processing = false;
    }
  } catch (err) {
    console.error('[worker] Transliteration-poll error:', err.message);
    processing = false;
  }
}

async function processTransliterationStage(parentDoc) {
  const parentRef = parentDoc.ref;
  const parent = parentDoc.data();
  console.log(`\n[worker] Transliterating ${parent.filename} (${parent.totalPages} pages)`);

  await parentRef.update({ status: 'assembling' });

  // Read all page docs in pageNum order. We transliterate per page so the UI
  // can render per-page collapsible sections (Sally's UX brief), and so verse
  // boundaries that align with page boundaries stay sensible.
  const pagesSnap = await parentRef.collection('pages').orderBy('pageNum').get();
  const pageDocs = pagesSnap.docs.filter(d => (d.data().gujaratiText ?? '').trim());
  const assembledGujarati = pageDocs
    .map(d => d.data().gujaratiText ?? '')
    .filter(Boolean)
    .join('\n\n');
  await parentRef.update({ gujaratiOutput: assembledGujarati, status: 'transliterating' });

  // Per-page transliteration: each page's gujaratiText becomes that page's
  // transliteratedText on the page doc. Long pages still get chunked
  // internally to stay under Sonnet's context window. Batches of 4 page-
  // jobs run in parallel.
  try {
    const system = await getTransliteratorSystem();
    const PAGE_BATCH = 4;
    let done = 0;

    async function transliteratePage(pageDoc) {
      const pageData = pageDoc.data();
      const guj = pageData.gujaratiText ?? '';
      if (!guj.trim()) return;
      // Skip if already done (resume support).
      if ((pageData.transliteratedText ?? '').trim()) { done++; return; }

      const chunks = deterministicChunk(guj);
      const chunkOuts = [];
      for (const chunk of chunks) {
        const prompt = `Transliterate the following Gujarati passage into Roman script per the rules above. Output ONLY <transliteration>…</transliteration>.\n\nGUJARATI:\n${chunk}`;
        const raw = await callClaude({
          model: SONNET, max_tokens: 8192,
          system,
          messages: [{ role: 'user', content: prompt }],
        });
        const match = raw.match(/<transliteration>([\s\S]*?)<\/transliteration>/);
        if (!match) throw new Error(`page ${pageData.pageNum}: transliterator did not return <transliteration> block`);
        chunkOuts.push(rulesEnforcerAgent(match[1].trim()).text);
      }
      const pageTranslit = chunks.length > 1
        ? rulesEnforcerAgent(assemblerAgent(chunkOuts)).text
        : chunkOuts[0] ?? '';
      await pageDoc.ref.update({ transliteratedText: pageTranslit });
      done++;
      console.log(`    ✓ page ${pageData.pageNum}/${parent.totalPages} → ${pageTranslit.split(/\s+/).length} words`);
    }

    for (let start = 0; start < pageDocs.length; start += PAGE_BATCH) {
      const slice = pageDocs.slice(start, start + PAGE_BATCH);
      await Promise.all(slice.map(transliteratePage));
    }

    // Assemble doc-level output by joining per-page transliterations. The UI
    // can also render from page docs directly; transliteratedOutput exists
    // for download exports and admin / overview consumers.
    const finalPagesSnap = await parentRef.collection('pages').orderBy('pageNum').get();
    const assembledTranslit = finalPagesSnap.docs
      .map(d => d.data().transliteratedText ?? '')
      .filter(Boolean)
      .join('\n\n');
    const finalTranslit = rulesEnforcerAgent(assembledTranslit).text;

    await parentRef.update({
      transliteratedOutput: finalTranslit,
      status: 'done',
      completedAt: new Date().toISOString(),
    });
    pdfCache.delete(parentRef.id);
    console.log(`  ✓ transliteration complete — ${finalTranslit.split(/\s+/).length} words across ${pageDocs.length} pages`);
  } catch (err) {
    console.error(`[worker] Transliteration failed: ${err.message}`);
    await parentRef.update({
      status: 'failed',
      error: `Transliteration: ${err.message?.slice(0, 200)}`,
      completedAt: new Date().toISOString(),
    });
    pdfCache.delete(parentRef.id);
  }
}

async function processTranslationStage(parentDoc) {
  const parentRef = parentDoc.ref;
  const parent = parentDoc.data();
  console.log(`\n[worker] Translating ${parent.filename} (optional secondary stage)`);

  await parentRef.update({ translationStatus: 'running' });
  try {
    // Run the canonical translator → enforcer → smoother → enforcer chain over
    // the assembled Gujarati, chunked. Mirrors the existing /jobs/ pipeline.
    const chunks = deterministicChunk(parent.gujaratiOutput ?? '');
    if (chunks.length === 0) throw new Error('No Gujarati content to translate');
    console.log(`  Chunked into ${chunks.length} piece${chunks.length === 1 ? '' : 's'}`);

    const translations = new Array(chunks.length).fill('');
    const smoothed = new Array(chunks.length).fill('');

    for (let start = 0; start < chunks.length; start += BATCH) {
      const slice = chunks.slice(start, start + BATCH);
      await Promise.all(slice.map(async (chunk, k) => {
        const i = start + k;
        // Translate
        const tOut = await translatorAgent(chunk, i, chunks.length);
        translations[i] = rulesEnforcerAgent(tOut.translation).text;
        console.log(`    ✓ translated chunk ${i + 1}/${chunks.length}`);
        // Smooth
        try {
          const sOut = await smootherAgent(translations[i]);
          smoothed[i] = rulesEnforcerAgent(sOut.smoothed).text;
        } catch (err) {
          console.warn(`    ⚠ smoother fallback on chunk ${i + 1}: ${err.message}`);
          smoothed[i] = translations[i];
        }
        console.log(`    ✓ smoothed chunk ${i + 1}/${chunks.length}`);
      }));
    }

    const assembledEn = assemblerAgent(smoothed);
    const finalEn = rulesEnforcerAgent(assembledEn).text;

    await parentRef.update({
      translationOutput: finalEn,
      translationStatus: 'done',
    });
    console.log(`  ✓ translation complete — ${finalEn.split(/\s+/).length} words across ${chunks.length} chunks`);
  } catch (err) {
    console.error(`[worker] Translation failed: ${err.message}`);
    await parentRef.update({
      translationStatus: 'failed',
      translationError: err.message?.slice(0, 200) ?? 'Unknown',
    });
  }
}

// ── Start ────────────────────────────────────────────────────────────────────

console.log('[worker] Aksharpith local worker started (using claude CLI — Max subscription)');
console.log(`[worker] Worker id: ${WORKER_ID}`);
console.log(`[worker] Polling Firestore every ${POLL_INTERVAL / 1000}s for jobs + extractions + transliterations...`);

// Initial poll
pollForJobs();

// Continuous polling — round-robin across the four queues.
let pollCycle = 0;
setInterval(() => {
  const phase = pollCycle % 4;
  if (phase === 0) pollForJobs();
  else if (phase === 1) pollForExtractions();
  else if (phase === 2) pollForPageJobs();
  else pollForTransliterationJobs();
  pollCycle++;
}, POLL_INTERVAL);

// Keep process alive
process.on('SIGINT', () => {
  console.log('\n[worker] Shutting down...');
  process.exit(0);
});
process.on('SIGTERM', () => {
  console.log('\n[worker] Shutting down...');
  process.exit(0);
});
